# Generated by Django 3.1 on 2020-11-21 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=210)),
                ('author', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('slug', models.CharField(default='', max_length=130)),
                ('timestamp', models.DateTimeField(blank=True)),
            ],
        ),
    ]
