# Generated by Django 3.1 on 2020-11-27 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20201121_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='image',
            new_name='thumbnail',
        ),
    ]
