# Generated by Django 3.1 on 2020-11-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20201127_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='thumbnail',
            field=models.ImageField(default='', upload_to='images/events'),
        ),
    ]
