# Generated by Django 3.1 on 2020-11-27 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20201127_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='sno',
            new_name='post_id',
        ),
    ]
