# Generated by Django 3.1 on 2020-11-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pdffile',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('head', models.CharField(default='', max_length=500)),
                ('pdf', models.ImageField(upload_to='media/pdf')),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
