# Generated by Django 3.1 on 2020-11-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pdf',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=110)),
                ('head', models.CharField(max_length=110)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
