# Generated by Django 3.1 on 2020-11-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0002_pdf'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pdffile',
        ),
        migrations.AddField(
            model_name='pdf',
            name='pdfile',
            field=models.ImageField(default='', upload_to='media/pdfs'),
        ),
    ]
