# Generated by Django 3.1 on 2020-11-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_club_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='image',
            field=models.ImageField(default='', upload_to='media/images/club'),
        ),
    ]
