# Generated by Django 3.1 on 2020-11-27 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_club_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='sno',
            new_name='post_id',
        ),
    ]
